name: Build & Create Docker Image

on:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string

jobs:

  verify:
    runs-on: [self-hosted, X64]
    container: maven:3.8.6-jdk-11
    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: maven

      - name: Verify
        run: mvn -B verify

  build:
    needs: verify
    runs-on: [self-hosted, X64]
    container: maven:3.8.6-jdk-11
    
    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: maven

      - name: Build
        run: mvn -B clean install
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: target/*.jar
          retention-days: 1  
      
  image:
    needs: build
    runs-on: [self-hosted, X64]

    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar

      - name: Create Image
        run: |
          mkdir -p extracted
          java -Djarmode=layertools -jar *.jar extract --destination extracted
          docker build -t ${{ inputs.image-name }} .

          docker image tag ${{ inputs.image-name }} 192.168.7.17:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker image tag ${{ inputs.image-name }} 192.168.7.17:5000/${{ inputs.image-name }}:latest
          
          docker push 192.168.7.17:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker push 192.168.7.17:5000/${{ inputs.image-name }}:latest

          docker image remove ${{ inputs.image-name }}
          docker image remove 192.168.7.17:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker image remove 192.168.7.17:5000/${{ inputs.image-name }}:latest