name: Build & Create Docker Image

on:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string

jobs:

  verify:
    runs-on: [ self-hosted, X64 ]
    #container: maven:3.8.6-jdk-11
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Verify
        run: mvn -B verify

  build:
    needs: verify
    runs-on: [ self-hosted, X64 ]
    #container: maven:3.8.6-jdk-11
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B clean install
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: target/*.jar
      
  image:
    needs: build
    strategy:
      matrix:
        arch: [X64, ARM64]
    runs-on: ${{ matrix.arch }}

    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      
      - name: Create Image
        run: |

          architect=$(dpkg --print-architecture)
          final_image_name=${{ inputs.image-name }}-${architect}

          mkdir -p extracted
          java -Djarmode=layertools -jar *.jar extract --destination extracted
          docker build -t ${final_image_name} .

          docker image tag ${final_image_name} 192.168.7.17:5000/${final_image_name}:$(date "+%Y%m%d")
          docker image tag ${final_image_name} 192.168.7.17:5000/${final_image_name}:latest
          
          docker push 192.168.7.17:5000/${final_image_name}:$(date "+%Y%m%d")
          docker push 192.168.7.17:5000/${final_image_name}:latest

          docker image remove ${final_image_name}
          docker image remove 192.168.7.17:5000/${final_image_name}:$(date "+%Y%m%d")
          docker image remove 192.168.7.17:5000/${final_image_name}:latest
  
  delete-artifact:
    needs: [build, image]
    runs-on: [ self-hosted, X64 ]
    steps:
      - name: Delete Artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: spring-boot-jar
