name: Build & Create Docker Image

on:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string

jobs:

  verify:
    runs-on: [self-hosted, X64]
    container: maven:3.8.6-jdk-11
    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: maven

      - name: Verify
        run: mvn -B verify

  image-build:
    needs: verify
    runs-on: [self-hosted, X64]
    container: maven:3.8.6-jdk-11
    
    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: maven

      - name: Build
        run: mvn -B clean install
        
      - name: Create Image
        run: |
          mkdir target/extracted
          java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted
          docker build -t ${{ inputs.image-name }} .

          docker image tag ${{ inputs.image-name }} localhost:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker image tag ${{ inputs.image-name }} localhost:5000/${{ inputs.image-name }}:latest
          
          docker push localhost:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker push localhost:5000/${{ inputs.image-name }}:latest

          docker image remove ${{ inputs.image-name }}
          docker image remove localhost:5000/${{ inputs.image-name }}:$(date "+%Y%m%d")
          docker image remove localhost:5000/${{ inputs.image-name }}:latest
